name: Test PR Merge 
on:
  pull_request:
    types:
      - closed

jobs:
  push-merge-commit-tag:
    name: Push merge commit tag
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - id: dump-github-context
      name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"